import React from "react";

export const styles = {
  page: { fontFamily: "'Inter', sans-serif", background: "#F3F1EC", minHeight: "100vh", color: "#2C2F2A", paddingBottom: 100, overscrollBehaviorY: "contain" },
  gatePage: { fontFamily: "'Inter', sans-serif", background: "#1F2422", minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  gateCard: { background: "#F3F1EC", borderRadius: 8, padding: "26px 24px", width: "100%", maxWidth: 340, display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center", borderTop: "4px solid #C1272D" },
  gateBrand: { display: "flex", alignItems: "center", gap: 6, fontSize: 11, fontWeight: 700, color: "#C1272D", letterSpacing: "0.08em", marginBottom: 14 },
  gateTitle: { fontFamily: "'Oswald', sans-serif", fontSize: 18, fontWeight: 600, marginBottom: 6 },
  gateSub: { fontSize: 12.5, color: "#8A8C86", lineHeight: 1.4, marginBottom: 16 },
  gateInput: { width: "100%", padding: "11px 12px", borderRadius: 6, border: "1.5px solid #E2DFD6", fontSize: 15, background: "white", marginTop: 4, textAlign: "center" },
  gateBtn: { width: "100%", marginTop: 12, background: "#C1272D", color: "white", border: "none", borderRadius: 6, padding: "11px 14px", fontSize: 14.5, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", gap: 4 },
  backLink: { marginTop: 14, background: "transparent", border: "none", color: "#8A8C86", fontSize: 12.5, fontWeight: 600, display: "flex", alignItems: "center", gap: 5 },
  rosterList: { display: "flex", flexDirection: "column", gap: 6, width: "100%", maxHeight: 220, overflowY: "auto", marginTop: 6 },
  rosterItem: { width: "100%", padding: "10px 12px", borderRadius: 6, border: "1.5px solid #E2DFD6", background: "white", fontSize: 14, fontWeight: 500, textAlign: "left", color: "#2C2F2A", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 8 },
  adminTag: { fontSize: 9.5, fontWeight: 700, color: "#C1272D", background: "#FBEAEA", padding: "1px 6px", borderRadius: 3, textTransform: "uppercase" },
  adminTagHeader: { fontSize: 9.5, fontWeight: 700, color: "#1F2422", background: "#E8A33D", padding: "1px 6px", borderRadius: 3, textTransform: "uppercase", marginLeft: 4 },
  funktionTag: { fontSize: 9, fontWeight: 700, color: "#4A6670", background: "#EAF0F1", padding: "1px 5px", borderRadius: 3, marginLeft: 5 },
  pinPendingTag: { fontSize: 9, fontWeight: 700, color: "#B8791A", background: "#FBF1E1", padding: "1px 6px", borderRadius: 3, textTransform: "uppercase", marginLeft: 5 },
  miniBereichTag: { display: "inline-flex", alignItems: "center", gap: 3, fontSize: 9.5, fontWeight: 700, color: "#5C5F58", background: "#EEEEEC", padding: "1px 6px", borderRadius: 3 },
  miniBereichTagDark: { display: "inline-flex", alignItems: "center", gap: 3, fontSize: 9.5, fontWeight: 700, color: "#B8BCB6", background: "#2C2F2A", padding: "1px 6px", borderRadius: 3 },

  header: { background: "#1F2422", padding: "16px 20px 12px" },
  headerTop: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  headerBrand: { display: "flex", alignItems: "center", gap: 9 },
  headerBrandText: { fontFamily: "'Oswald', sans-serif", fontWeight: 600, fontSize: 15.5, letterSpacing: "0.04em", color: "#F3F1EC", lineHeight: 1.2 },
  headerBrandSub: { fontSize: 10.5, color: "#8FA0A6", fontWeight: 500, letterSpacing: "0.03em" },
  settingsBtn: { background: "transparent", border: "none", padding: 4 },
  headerMe: { display: "flex", alignItems: "center", gap: 5, fontSize: 11.5, color: "#8FA0A6", marginTop: 10, flexWrap: "wrap" },
  switchLink: { background: "transparent", border: "none", color: "#E8A33D", fontSize: 11.5, fontWeight: 600, textDecoration: "underline", padding: 0, marginLeft: 4 },
  bereichRow: { display: "flex", gap: 6, marginTop: 10, flexWrap: "wrap" },
  bereichChip: { display: "flex", alignItems: "center", gap: 4, fontSize: 10.5, fontWeight: 700, color: "#F3F1EC", background: "transparent", border: "1.5px solid", borderRadius: 14, padding: "3px 8px" },
  iosHintBanner: { display: "flex", alignItems: "flex-start", gap: 8, marginTop: 10, background: "#2C2F2A", borderRadius: 6, padding: "8px 10px", fontSize: 10.5, color: "#B8BCB6", lineHeight: 1.4 },
  iosHintClose: { background: "transparent", border: "none", padding: 0, flexShrink: 0 },

  errorBanner: { position: "sticky", top: 0, zIndex: 40, background: "#C1272D", color: "white", fontSize: 12.5, fontWeight: 600, padding: "9px 16px", display: "flex", alignItems: "center", gap: 8 },

  remindersSection: { padding: "14px 16px 0" },
  reminderCard: { display: "flex", alignItems: "flex-start", gap: 9, background: "#FBF1E1", border: "1px solid #E8C98A", borderRadius: 6, padding: "10px 12px", marginBottom: 8 },
  reminderText: { fontSize: 12.5, color: "#6B4E12", lineHeight: 1.4, fontWeight: 500 },
  reminderDoctor: { fontSize: 11, color: "#8A6B2E", marginTop: 4 },
  reminderOk: { background: "#B8791A", color: "white", border: "none", borderRadius: 4, padding: "4px 10px", fontSize: 11, fontWeight: 700, flexShrink: 0 },

  noticesSection: { padding: "16px 16px 4px" },
  sectionLabelRow: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 8, marginLeft: 4, marginRight: 2 },
  sectionLabel: { display: "flex", alignItems: "center", gap: 6, fontSize: 11, fontWeight: 700, color: "#5C5F58", letterSpacing: "0.08em" },
  smallAddBtn: { display: "flex", alignItems: "center", gap: 3, background: "transparent", border: "1px solid #C1272D", color: "#C1272D", borderRadius: 14, padding: "3px 9px", fontSize: 11, fontWeight: 700 },
  noNotices: { fontSize: 12, color: "#8A8C86", padding: "4px 4px 8px" },
  noticeCard: { display: "flex", gap: 10, alignItems: "flex-start", borderLeft: "3.5px solid", borderRadius: 4, padding: "10px 12px", marginBottom: 7 },
  noticeBadge: { fontSize: 9, fontWeight: 700, color: "white", padding: "2px 6px", borderRadius: 3, textTransform: "uppercase" },
  noticeExpiry: { fontSize: 10.5, color: "#8A8C86" },
  noticeText: { fontSize: 13, color: "#2C2F2A", lineHeight: 1.4 },

  hero: { padding: "16px 16px 4px" },
  heroLabel: { display: "flex", alignItems: "center", gap: 6, fontSize: 11, fontWeight: 700, color: "#C1272D", letterSpacing: "0.08em", marginBottom: 8, marginLeft: 4 },
  heroCard: { background: "#1F2422", borderRadius: 4, padding: "16px 14px", borderLeft: "4px solid #C1272D" },
  heroDateBlock: { textAlign: "center", width: 46, flexShrink: 0 },
  heroDay: { fontFamily: "'JetBrains Mono', monospace", fontSize: 30, fontWeight: 700, color: "white", lineHeight: 1 },
  heroMonth: { fontFamily: "'JetBrains Mono', monospace", fontSize: 11, color: "#8FA0A6", letterSpacing: "0.05em", marginTop: 2 },
  heroDivider: { width: 1, alignSelf: "stretch", background: "#3A3F3B" },
  heroRel: { fontSize: 11, fontWeight: 700, color: "#E8A33D", letterSpacing: "0.04em" },
  heroTitle: { fontFamily: "'Oswald', sans-serif", fontSize: 17, fontWeight: 600, color: "white", lineHeight: 1.2, marginBottom: 5 },
  heroMeta: { display: "flex", gap: 12, flexWrap: "wrap" },
  heroMetaItem: { display: "flex", alignItems: "center", gap: 4, fontSize: 12, color: "#B8BCB6" },
  heroBadge: { fontSize: 9, fontWeight: 700, color: "white", padding: "3px 7px", borderRadius: 3, letterSpacing: "0.04em", textTransform: "uppercase", alignSelf: "flex-start" },
  heroRespRow: { display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 14, paddingTop: 12, borderTop: "1px solid #3A3F3B", flexWrap: "wrap", gap: 8 },
  heroCounts: { fontSize: 11.5, color: "#8FA0A6" },

  tabRow: { display: "flex", flexWrap: "wrap", gap: 6, padding: "16px 16px 4px" },
  tabBtn: { fontSize: 11.5, fontWeight: 600, padding: "5px 10px", borderRadius: 16, border: "1.5px solid", whiteSpace: "nowrap" },
  tabDot: { position: "absolute", top: -2, right: -2, width: 8, height: 8, borderRadius: "50%", background: "#E8A33D", border: "1.5px solid #F3F1EC" },

  main: { padding: "18px 16px 0" },
  monthLabel: { fontFamily: "'Oswald', sans-serif", fontSize: 12.5, fontWeight: 600, color: "#8A8C86", letterSpacing: "0.06em", textTransform: "uppercase", marginBottom: 10, paddingLeft: 2 },

  eventCard: { background: "white", borderRadius: 3, borderLeft: "3.5px solid", padding: "12px 12px", marginBottom: 8, boxShadow: "0 1px 2px rgba(0,0,0,0.04)" },
  eventDateCol: { textAlign: "center", width: 34, flexShrink: 0, paddingTop: 1 },
  eventDay: { fontFamily: "'JetBrains Mono', monospace", fontSize: 19, fontWeight: 700, color: "#2C2F2A", lineHeight: 1 },
  eventWeekday: { fontFamily: "'JetBrains Mono', monospace", fontSize: 9.5, color: "#A5A79F", marginTop: 2, textTransform: "uppercase" },
  eventTitleRow: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 8, marginBottom: 4 },
  eventTitle: { fontSize: 14.5, fontWeight: 600, color: "#2C2F2A", lineHeight: 1.3 },
  eventBadge: { fontSize: 9.5, fontWeight: 700, padding: "2px 6px", borderRadius: 3, whiteSpace: "nowrap", flexShrink: 0 },
  eventMeta: { display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 2 },
  eventMetaItem: { display: "flex", alignItems: "center", gap: 3, fontSize: 11.5, color: "#8A8C86" },
  eventNotes: { fontSize: 12, color: "#9A9C95", marginTop: 4, lineHeight: 1.4 },
  editBtn: { padding: 5, borderRadius: 4, background: "transparent", border: "none", flexShrink: 0, height: "fit-content" },
  eventRespFooter: { display: "flex", alignItems: "center", justifyContent: "space-between", marginTop: 10, paddingTop: 10, borderTop: "1px solid #F0EEE7", flexWrap: "wrap", gap: 6 },
  expandLink: { background: "transparent", border: "none", fontSize: 11.5, color: "#4A6670", fontWeight: 600, padding: 0 },
  expandPanel: { marginTop: 8, paddingTop: 8, borderTop: "1px dashed #E2DFD6", display: "flex", flexDirection: "column", gap: 3 },
  expandLine: { fontSize: 12, color: "#5C5F58", lineHeight: 1.5 },

  capacityCounterRow: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 2, maxWidth: "55%" },
  capacityNames: { fontSize: 10.5, color: "#8A8C86", textAlign: "right", lineHeight: 1.3 },
  capacityNamesHidden: { display: "flex", alignItems: "center", gap: 3, fontSize: 10.5, color: "#A5A79F" },

  respBtn: { display: "flex", alignItems: "center", gap: 5, fontSize: 12.5, fontWeight: 600, padding: "7px 12px", borderRadius: 6, border: "1.5px solid" },
  respBtnSmall: { fontSize: 11, padding: "5px 9px", gap: 4 },

  emptyState: { textAlign: "center", padding: "50px 20px", display: "flex", flexDirection: "column", alignItems: "center" },
  fab: { position: "fixed", bottom: 22, right: 20, width: 52, height: 52, borderRadius: "50%", background: "#C1272D", border: "none", display: "flex", alignItems: "center", justifyContent: "center", boxShadow: "0 3px 10px rgba(193,39,45,0.4)" },

  modalBackdrop: { position: "fixed", inset: 0, background: "rgba(31,36,34,0.55)", display: "flex", alignItems: "flex-end", zIndex: 70 },
  modalSheet: { background: "#F3F1EC", width: "100%", maxHeight: "88vh", overflowY: "auto", borderRadius: "14px 14px 0 0", padding: "14px 18px 24px" },
  modalHeader: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 14 },
  modalTitle: { fontFamily: "'Oswald', sans-serif", fontSize: 17, fontWeight: 600, color: "#2C2F2A" },
  iconBtn: { background: "transparent", border: "none", padding: 4, borderRadius: 4 },

  formBody: { display: "flex", flexDirection: "column", gap: 4 },
  label: { fontSize: 11.5, fontWeight: 700, color: "#8A8C86", letterSpacing: "0.03em", marginTop: 10, marginBottom: 5 },
  input: { width: "100%", padding: "10px 11px", borderRadius: 6, border: "1.5px solid #E2DFD6", fontSize: 14.5, background: "white", color: "#2C2F2A" },
  categoryPicker: { display: "flex", flexWrap: "wrap", gap: 6 },
  categoryChip: { fontSize: 12.5, fontWeight: 600, padding: "6px 12px", borderRadius: 20, border: "1.5px solid", display: "flex", alignItems: "center", gap: 4 },
  errorText: { color: "#C1272D", fontSize: 12.5, marginTop: 10, fontWeight: 500 },
  formActions: { display: "flex", gap: 10, marginTop: 20 },
  deleteBtn: { display: "flex", alignItems: "center", gap: 6, background: "transparent", border: "1.5px solid #E2A9A9", color: "#C1272D", borderRadius: 6, padding: "10px 14px", fontSize: 13.5, fontWeight: 600 },
  saveBtn: { flex: 1, background: "#C1272D", color: "white", border: "none", borderRadius: 6, padding: "11px 14px", fontSize: 14.5, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center" },

  capacityBox: { background: "white", border: "1.5px solid #E2DFD6", borderRadius: 8, padding: "12px 12px", marginTop: 12 },
  checkboxRow: { display: "flex", alignItems: "flex-start", gap: 8, fontSize: 12.5, color: "#2C2F2A", lineHeight: 1.4, cursor: "pointer" },

  rosterManageList: { display: "flex", flexDirection: "column", gap: 8, maxHeight: 380, overflowY: "auto" },
  rosterManageItemFull: { background: "white", padding: "9px 10px", borderRadius: 6, border: "1px solid #E2DFD6", fontSize: 13.5 },
  rosterRemoveBtn: { background: "transparent", border: "none", padding: 3, color: "#8A8C86" },

  kontrollTab: { display: "flex", alignItems: "center", gap: 5, fontSize: 12.5, fontWeight: 600, padding: "6px 12px", borderRadius: 20, border: "1.5px solid #E2DFD6", background: "white", color: "#5C5F58" },
  kontrollTabActive: { background: "#2C2F2A", color: "white", borderColor: "#2C2F2A" },
  kontrollRow: { background: "white", border: "1px solid #E2DFD6", borderRadius: 6, padding: "9px 10px", marginBottom: 6 },
  exportBtn: { display: "flex", alignItems: "center", gap: 6, background: "#4A6670", color: "white", border: "none", borderRadius: 6, padding: "9px 14px", fontSize: 12.5, fontWeight: 600, marginBottom: 4 },
  tinyBtn: { fontSize: 10.5, fontWeight: 600, padding: "3px 8px", borderRadius: 4, border: "1px solid #E2DFD6", background: "#F3F1EC", color: "#5C5F58" },
  tinyIconBtn: { display: "inline-flex", alignItems: "center", justifyContent: "center", padding: "3px 5px", borderRadius: 4, border: "1px solid #E2DFD6", background: "#F3F1EC", color: "#5C5F58", flexShrink: 0 },
  lightboxBackdrop: { position: "fixed", inset: 0, background: "rgba(20,20,20,0.92)", zIndex: 90, display: "flex", alignItems: "center", justifyContent: "center", padding: 20 },
  lightboxImg: { maxWidth: "95vw", maxHeight: "90vh", objectFit: "contain", borderRadius: 4 },
  lightboxClose: { position: "fixed", top: 16, right: 16, background: "rgba(255,255,255,0.15)", border: "none", borderRadius: "50%", padding: 8, zIndex: 91, display: "flex", alignItems: "center", justifyContent: "center" },
  tinyBtnPrimary: { fontSize: 10.5, fontWeight: 700, padding: "3px 8px", borderRadius: 4, border: "1px solid #1F6F5C", background: "#1F6F5C", color: "white" },
  tileGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  tile: { display: "flex", flexDirection: "column", alignItems: "center", gap: 8, background: "#FBF1E1", border: "0.5px solid #E8C98A", borderRadius: 12, padding: "18px 10px", position: "relative" },
  fullscreenPage: { position: "fixed", inset: 0, background: "#F3F1EC", zIndex: 60, overflowY: "auto", padding: "20px 18px 40px" },
  fullscreenHeader: { display: "flex", alignItems: "center", marginBottom: 12 },
  fullscreenBackBtn: { display: "flex", alignItems: "center", gap: 5, background: "transparent", border: "none", color: "#5C5F58", fontSize: 13, fontWeight: 600, padding: 0 },
  tileLabel: { fontSize: 12.5, fontWeight: 600, color: "#2C2F2A" },
  tileBadge: { position: "absolute", top: 8, right: 8, minWidth: 18, height: 18, borderRadius: 9, background: "#E8A33D", color: "white", fontSize: 10.5, fontWeight: 700, display: "flex", alignItems: "center", justifyContent: "center", padding: "0 4px" },
  tilePlaceholder: { display: "flex", flexDirection: "column", alignItems: "center", gap: 8, background: "#F3F1EC", border: "1px dashed #C7C4BC", borderRadius: 12, padding: "18px 10px" },
  tileHeaderDot: { position: "absolute", top: 4, right: 4, width: 8, height: 8, borderRadius: "50%", background: "#E8A33D" },
  teaserSection: { padding: "0 16px 4px" },
  teaserCard: { display: "flex", alignItems: "center", gap: 10, width: "100%", background: "#F1E9F6", border: "1px solid #DCC8EA", borderRadius: 8, padding: "10px 12px", marginBottom: 8 },
  confirmDialog: { background: "#F3F1EC", borderRadius: 10, padding: "22px 20px", width: "100%", maxWidth: 320, display: "flex", flexDirection: "column", alignItems: "center", textAlign: "center", margin: "auto" },
  advancedToggle: { display: "flex", alignItems: "center", gap: 5, background: "transparent", border: "none", color: "#8A8C86", fontSize: 11.5, fontWeight: 600, padding: 0 },
  expandSitzungBtn: { display: "flex", alignItems: "center", gap: 4, background: "#EAF0F1", border: "1px solid #C7D4D8", color: "#4A6670", fontSize: 11, fontWeight: 700, padding: "5px 9px", borderRadius: 14, whiteSpace: "nowrap" },
  problemBanner: { display: "flex", alignItems: "center", gap: 6, background: "#FBEAEA", border: "1px solid #E2A9A9", borderRadius: 6, padding: "6px 9px", marginTop: 5, fontSize: 11.5, color: "#8A2A2A" },
  voteBox: { marginTop: 6, paddingTop: 6, borderTop: "1px dashed #E2DFD6" },
  voteNote: { fontSize: 11, color: "#8A8C86" },
  voteResultBox: { background: "#EAF0F1", borderRadius: 6, padding: "8px 10px", marginTop: 4 },
  voteAntrag: { fontSize: 12, fontStyle: "italic", color: "#4A6670", marginBottom: 5 },
  attendanceRow: { display: "flex", alignItems: "center", gap: 10, fontSize: 14, color: "#2C2F2A", padding: "9px 6px", borderRadius: 6, cursor: "pointer" },
  attendanceCheckbox: { width: 22, height: 22, flexShrink: 0, accentColor: "#1F6F5C" },
  guestStepper: { display: "flex", alignItems: "center", gap: 6, marginTop: 8 },
  gfTagSet: { display: "inline-flex", alignItems: "center", gap: 3, fontSize: 11, color: "#4A6670", fontWeight: 600 },
  gfTagMissing: { display: "inline-flex", alignItems: "center", color: "#E8A33D" },
};
